export const SET_SHOP_CATEGORY_PRODUCTS_DATA =
  'SET_SHOP_CATEGORY_PRODUCTS_DATA';
export const SET_SHOP_CATEGORY_PRODUCTS_ERROR =
  'SET_SHOP_CATEGORY_PRODUCTS_ERROR';
export const CLEAN_STATE = 'CLEAN_STATE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
